// FE/src/lib/components/TaskBar.svelte
<script lang="ts">
  import { LIMITS, type Task } from "@pp/shared";

  interface Props {
    task: Task | null;
    isHost: boolean;
    onsettask: (description: string) => void;
  }

  let { task, isHost, onsettask }: Props = $props();

  let draft = $state("");

  function submit(event: SubmitEvent): void {
    event.preventDefault();
    const description = draft.trim();
    if (!description) return;
    onsettask(description);
    draft = "";
  }
</script>

<section class="taskbar card-surface">
  <div class="current">
    <span class="label">Current task</span>
    <p class="text" class:none={!task}>
      {task ? task.description : "No task yet"}
    </p>
  </div>

  {#if isHost}
    <form class="set-form" onsubmit={submit}>
      <input
        class="input"
        type="text"
        placeholder="Describe the task to estimate…"
        bind:value={draft}
        maxlength={LIMITS.taskDescriptionMax}
        aria-label="Task description"
      />
      <button class="btn btn-primary" type="submit" disabled={!draft.trim()}>
        Set task
      </button>
    </form>
  {/if}
</section>

<style>
  .taskbar {
    padding: var(--space-5);
    display: flex;
    flex-direction: column;
    gap: var(--space-4);
  }

  .current {
    display: flex;
    flex-direction: column;
    gap: var(--space-1);
  }

  .label {
    font-size: var(--font-size-sm);
    color: var(--color-text-muted);
  }

  .text {
    font-size: var(--font-size-lg);
    font-weight: 600;
  }

  .text.none {
    color: var(--color-text-muted);
    font-weight: 400;
  }

  .set-form {
    display: flex;
    gap: var(--space-3);
  }

  .set-form .input {
    flex: 1;
  }

  .set-form .btn {
    white-space: nowrap;
  }

  @media (max-width: 520px) {
    .set-form {
      flex-direction: column;
    }
  }
</style>

// FE/src/components/TaskBar.tsx
import { useState } from "react";
import { LIMITS, type Task } from "@pp/shared";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import styles from "./TaskBar.module.css";

interface Props {
  task: Task | null;
  isHost: boolean;
  onSetTask: (description: string) => void;
}

export function TaskBar({ task, isHost, onSetTask }: Props) {
  const [draft, setDraft] = useState("");

  function handleSubmit(event: React.FormEvent<HTMLFormElement>): void {
    event.preventDefault();
    const description = draft.trim();
    if (!description) return;
    onSetTask(description);
    setDraft("");
  }

  return (
    <section className={styles.taskbar}>
      <div className={styles.current}>
        <span className={styles.label}>Current task</span>
        <p className={cn(styles.text, !task && styles.none)}>
          {task ? task.description : "No task yet"}
        </p>
      </div>

      {isHost && (
        <form className={styles.setForm} onSubmit={handleSubmit}>
          <Input
            type="text"
            placeholder="Describe the task to estimate…"
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            maxLength={LIMITS.taskDescriptionMax}
            aria-label="Task description"
            autoComplete="off"
            autoCapitalize="off"
            className={styles.input}
          />
          <Button type="submit" disabled={!draft.trim()} className={styles.btn}>
            Set task
          </Button>
        </form>
      )}
    </section>
  );
}
